### ISSUE TITLE
Doesn't work with cypress@5.0.0

### ISSUE THREAD

**Issue by marcin-piela-sf** [happo/happo-cypress#31]
Plugin doesn't work with newest version of cypress:

```
crypto.createHash is not a function
```

Had to install version 4 of cypress.

**Comment by trotzig** [comment]
Good catch! Let me try to fix this first thing tomorrow.

**Comment by trotzig** [comment]
My initial attempt at reproducing this came up short. I updated to Cypress@5 and nothing broke. 

There are three places we use `crypto.createHash`: 
- [When we extract CSS from the page](https://github.com/happo/happo-cypress/blob/fbdd5663f0a4a4d29a51203ef4e1f98ac8c59405/index.js#L39)
- [When we inline canvases as PNGs](https://github.com/happo/happo-cypress/blob/fbdd5663f0a4a4d29a51203ef4e1f98ac8c59405/index.js#L94)
- [When we create asset packages](https://github.com/happo/happo-cypress/blob/fbdd5663f0a4a4d29a51203ef4e1f98ac8c59405/src/createAssetPackage.js#L56)

The first two instances run in a browser environment. The last one runs in the main `cypress run` process (so not in a browser). I suspect you're getting the issue from one of the browser instances. Is there a stack trace you can post? 

Even though I can't reproduce this right now, I'm going to apply a fix anyway. The fact that there is a `crypto` module in the process running in the browser is sort of unexpected, so I'm going to use a browser-safe library instead (e.g. [crypto-js](https://www.npmjs.com/package/crypto-js)).

**Comment by trotzig** [comment]
Give [1.7.4](https://github.com/happo/happo-cypress/releases/tag/v1.7.4) a try and see if that makes things better! Appreciate the bug report.
